query Category($slug: String!) {
  categories(where: {slug: $slug}) {
    name
    slug
    articles {
      id
      title
      slug
      content
      image {
        url
      }
      category {
        id
        name
      }
    }
  }
}
